name: petOne
services:
    db:
        image: postgres
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_USER: pet_one
            POSTGRES_PASSWORD: pass123
            POSTGRES_DB: pet_one
        volumes:
            - pgData:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_VHOST=local
        volumes:
            - 'rabbitmq_data:/data'

    kafka:
        image: apache/kafka:latest
        hostname: broker
        container_name: broker
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_NODE_ID: 1
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
            KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
            CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        environment:
            DYNAMIC_CONFIG_ENABLED: true

    clickhouse-server:
        image: yandex/clickhouse-server
        container_name: clickhouse-server
        volumes:
#            - ./docker/clickhouse/:/etc/clickhouse-server/:rw
            - clickhouseDb:/var/lib/clickhouse
        ulimits:
            nofile: 262144

    twportainer:
        image: portainer/portainer-ce:latest
        container_name: twportainer
        environment:
            - TZ=Europe/Moscow
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/twportainer/portainer_data:/data
        ports:
            - "18000:8000"
            - "19443:9443"
        restart: always
    grafana:
        image: grafana/grafana-enterprise
        container_name: grafana
        restart: unless-stopped
        ports:
            - '3001:3000'
volumes:
    pgData:
    rabbitmq_data:
    clickhouseDb: