CREATE TABLE users
(
    id       BIGSERIAL NOT NULL PRIMARY KEY,
    login    VARCHAR   NOT NULL UNIQUE,
    password VARCHAR   NOT NULL
);

CREATE TABLE articles
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    title VARCHAR NOT NULL UNIQUE,
    author VARCHAR NOT NULL,
    content VARCHAR NOT NULL
);